name: SNOW PR Build

env:
  GH_TOKEN: ${{ github.token }}
  RELEASEURL: "https://github.com/${{ github.repository }}/releases/download"

on:
  pull_request:
    branches:
      - "main"

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Snow Desktop
    runs-on: generic
    steps:
      - name: install git
        run: |
          sudo apt-get update && sudo apt-get install -y git-core jq
      - name: setup-mkosi
        uses: systemd/mkosi@main
      - name: checkout repo
        uses: actions/checkout@main
      - name: Decrypt large secret
        run: ./scripts/decrypt_secrets.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
      - name: build
        run: |
          cp $HOME/secrets/mkosi.crt .
          cp $HOME/secrets/mkosi.key .
          chmod 600 ./mkosi.key
          mkosi -B
