name: SNOW Push Build

env:
  GH_TOKEN: ${{ github.token }}
  RELEASEURL: "https://github.com/${{ github.repository }}/releases/download"

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
# Needed to allow creating a release
permissions:
  contents: write

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Snow Desktop
    runs-on: generic
    steps:
      - name: install git
        run: |
          sudo apt-get update && sudo apt-get install -y git-core jq
      - name: setup-mkosi
        uses: systemd/mkosi@main
      - name: checkout repo
        uses: actions/checkout@main
      - name: Decrypt large secret
        run: ./scripts/decrypt_secrets.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
      - name: Pull latest brew tap
        run : |
          mkdir -p mkosi.extra/usr/share
          ./scripts/ghcurl "$(./scripts/ghcurl https://api.github.com/repos/linuxsnow/homebrew-tap/releases/latest | jq -r '.assets[] | select(.name| test(".*-x86_64.tar.zst$")).browser_download_url')" -Lo mkosi.extra/usr/share/homebrew.tar.zst
      - name: build
        run: |
          cp $HOME/secrets/mkosi.crt .
          cp $HOME/secrets/mkosi.key .
          chmod 600 ./mkosi.key
          mkosi -B
      - name: clean up output
        run: |
          rm -f mkosi.output/initrd
          rm -f mkosi.output/initrd.cpio.zst
          rm -rf mkosi.output/base
          ./scripts/sums.sh
      - name: scp output
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSHUSER }}
          key: ${{ secrets.KEY }}
          strip_components: 1
          source: "mkosi.output/*"
          target: /mnt/fast/snow/
      - name: concatenate shasums
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSHUSER }}
          key: ${{ secrets.KEY }}
          script_path: scripts/releases.sh
